### PR TITLE
Mopub click and Impression tracking

### PR DESCRIPTION
**Pull request by YuriAbgaryan**

### CODE REVIEW

**Comment by UnateD** [comment]
both methods (notifyAdImpressed / notifyAdClicked) now has protected access and not working

**Comment by alexskobozev** [comment]
> both methods (notifyAdImpressed / notifyAdClicked) now has protected access and not working

They had protected access previously. According MoPub documentation for mediation, a subclass of com.mopub.nativeads.CustomEventNative must be in the com.mopub.nativeads package. If so, these protected methods should work

**Comment by UnateD** [comment]
unfortunately, the situation is different with the current version of the MoPub mediation library ... You cannot call the specified methods in a subclass of CustomEventNative. The code from the MyTargetCustomEventNative class reports an error immediately after integration into the project for this reason

**Comment by alexskobozev** [comment]
Can you paste error text here?

**Pull request merged**
